name: docs

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  verify-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docs files and local links
        run: ./scripts/docs_check.sh
